# permissions for end users to view servings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serving-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: faas
    app.kubernetes.io/part-of: faas
    app.kubernetes.io/managed-by: kustomize
  name: serving-viewer-role
rules:
- apiGroups:
  - faas.czlingo.io
  resources:
  - servings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - faas.czlingo.io
  resources:
  - servings/status
  verbs:
  - get
