apiVersion: faas.czlingo.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: function
    app.kubernetes.io/instance: function-sample
    app.kubernetes.io/part-of: faas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: faas
  name: function-sample
spec:
  # TODO(user): Add fields here
  image: czlingo/funcsample
  build: 
    repo: git@github.com:czlingo/faas.git
    subpath: sample/cmd
  imageCredential: 
    name: secret-dockercfg
  sshCredential:
    name: git-ssh
